### ISSUE TITLE
第 35 期(W3C 标准-CSS-布局排版)：图片等比缩放匹配父容器尺寸

### ISSUE THREAD

**Issue by wingmeng** [fezaoduke/fe-practice-hard#38]
**题目：**

请使用纯 CSS 实现图片等比缩放最大化匹配父容器尺寸的效果：使下面的图片自适应填充父容器尺寸，同时保持宽高比。

**要求：**

- 图片不能变形
- 图片不能被剪裁
- 图片不能溢出父容器

**效果图：**
![image](https://user-images.githubusercontent.com/9009389/59603496-249f5d80-913c-11e9-9d16-00ecdbdcc7ad.png)

```css
.box {
  width: 300px;
  height: 200px;
  padding: 10px;
  border: 1px solid #ccc;
}
```

```html
<div class="box">
  <img src="https://fezaoduke.github.io/fe-practice-hard/assets/pics/cartoon.png">
</div>
```
