### ISSUE TITLE
第 46 期(W3C标准-CSS-动画)：按钮loading动画效果

### ISSUE THREAD

**Issue by wingmeng** [fezaoduke/fe-practice-hard#49]
**题目：**

请使用纯 CSS 实现 `.btn` 按钮的 loading 动画效果，效果如下图：

![GIF](https://user-images.githubusercontent.com/9009389/60397290-f11df380-9b7d-11e9-819e-ff3dcef529ae.gif)

相关的 CSS 和 HTML 已写好：

```css
.btn {
  display: inline-block;
  padding: .5em 1.2em;
  font-size: 14px;
  color: #fff;
  background: #369;
  border: 0;
  border-radius: 5px;
}
/* 请补充 loading 动画的 CSS 实现 */
```

```html
<button class="btn">确定</button>
<button class="btn loading">确定</button>
```
