### ISSUE TITLE
第 4 期(2019-05-11)：CSS 菱形剪切

### ISSUE THREAD

**Issue by wingmeng** [fezaoduke/fe-practice-hard#6]
> 来源：原创题
> 难度：★

**使用纯 CSS 将下面的图片进行菱形剪切。**

> 注：图片不允许拉伸、挤压。实现代码越简单越好。

```html
<!-- html -->
<img src="https://fezaoduke.github.io/fe-practice-hard/assets/pics/cartoon.png">
```

```css
/* css */
img {
  /* 你的代码 */
}
```

**参考效果图：**

![image](https://user-images.githubusercontent.com/9009389/57569774-8b8a7200-742c-11e9-9314-ba0cd4432113.png)

**Comment by liwenkang** [comment]
```css
img{
    /* polygon 中的参数是多边形的顶点 */
    clip-path: polygon(50% 0, 100% 50%, 50% 100%, 0 50%);
}
```
